#!/bin/sh

# todo  : 断线重连功能未加入
# 极客模式自动打开及极客密码的显示未处理

PACKAGE_NAME="com.modouwifi.app-ssh-reverse"
PWD="$(cd $(dirname $0) && pwd)"
TITLE="远程协助"
PROGRAM_NAME="app-ssh-reverse"
CUSTOM_BIN="/system/apps/tp/bin/custom"


APPS_CONFIG_DIR="/data/conf"
LAUNCHER_CONFIG_DIR="$APPS_CONFIG_DIR/launcher/conf.d"
LAUNCHER_CONFIG_FILE="$LAUNCHER_CONFIG_DIR/$PROGRAM_NAME.conf"

ICON="./res/icon.png"
PRESSED_ICON="./res/icon_pressed.png"

INSTALL_BIN="/usr/bin/install"
REMOVE="/bin/rm -f"

SERVER="118.144.72.156"
KEY_FILE=$PWD/id_rsa
SSH=$PWD/ssh
USER="help"
SSH_CONFIG="$PWD/ssh_config"

usage() {
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}

remote_exec()
{
    exec_result=`$SSH -i $KEY_FILE -F $SSH_CONFIG $USER@$SERVER "$1"`    
}

get_port()
{
    local netstat="busy"
    local portlist=1

    while [ "$netstat" != "" -o "$portlist" != "0" ] 
    do
        # 可以考虑用/dev/random实现，且是1024以上即可
        local RAN_NUM=`date +%s` 
        local t1=`expr $RAN_NUM % 50000`
        port_result=`expr $t1 + 1030`

        remote_exec "netstat -an | grep $port_result"
        netstat=$exec_result
        remote_exec "cat port.list | grep $port_result | wc -l"
        portlist=$exec_result
    done
}

start_service()
{
    # 随机取得端口
    get_port; 
    local port=$port_result
    
    echo "使用PORT:$port"
    $SSH -i $KEY_FILE -F $SSH_CONFIG -g -NfR *:$port:*:22 $USER@$SERVER

    json4sh.sh set $PWD/conf/data.json current_port value $port

    local pass=`nvram_get 2860 Password`
    json4sh.sh set $PWD/conf/data.json current_pass value $pass

    appInfo.sh set_status "$PACKAGE_NAME" ISRUNNING
}

run() {
    local status=`appInfo.sh get_status "$PACKAGE_NAME"`
    local new_start=0

    # 如果服务还没有开启,则开启服务
    if [ "$status" == "NOTRUNNING" ] ; then        
        new_start=1

        # 添加转菊花效果 -- 阿耀 2014-10-29
        updateconf $PWD/loading.conf -t State -v 0
        loadingapp $PWD/loading.conf &

        start_service
    fi

    # 显示当前服务端口
    local port=`json4sh.sh get $PWD/conf/data.json current_port value`
    local pass=`json4sh.sh get $PWD/conf/data.json current_pass value`
    
    messagebox 远程协助 "远程协助已开启,服务序号
$port。
当前极客密码:$pass
协助结束后请退出。" 1 结束 "$PWD/init stop" &

    # 停止转菊花
    if [ "$new_start" == "1" ] ; then        
        updateconf $PWD/loading.conf -t State -v 2
    fi
    
}

start() {
    start_service
}

stop() {
    killall ssh
    json4sh.sh set $PWD/conf/data.json current_port value 空
    json4sh.sh set $PWD/conf/data.json current_pass value 空
    appInfo.sh set_status "$PACKAGE_NAME" NOTRUNNING
}

config() {
    echo "{" > "$PROGRAM_NAME.conf"
    echo "\"name\" :  \"$TITLE\"," >> "$PROGRAM_NAME.conf"
    echo "\"icon\" : \"$PWD/$ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"iconPressed\" : \"$PWD/$PRESSED_ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"exec\" : \"$PWD/init run\"," >> "$PROGRAM_NAME.conf"
    echo "\"msgNum\" : 4" >> "$PROGRAM_NAME.conf"
    echo "}" >> "$PROGRAM_NAME.conf"

    $INSTALL_BIN -d $LAUNCHER_CONFIG_DIR
    $INSTALL_BIN "$PROGRAM_NAME.conf" "$LAUNCHER_CONFIG_FILE"
    $REMOVE "$PROGRAM_NAME.conf"
    
    chmod 600 $PWD/id_rsa
}

uninstall() {
    $REMOVE "$LAUNCHER_CONFIG_FILE"
}

# main
if [ $# -lt 1 ]; then
    usage
    exit 255
fi

case "$1" in
    "start" )
        start;;
    "stop" )
        stop;;
    "restart" )
        start
        stop;;
    "run" )
        run;;
    "install" )
        config;;
    "uninstall" )
        uninstall;;
    * )
        usage ;;
esac
