#!/bin/sh

PWD="$(cd $(dirname $0) && pwd)"
TITLE="远程协助"
PROGRAM_NAME="app-ssh-reverse"
CUSTOM_BIN="/system/apps/tp/bin/custom"

APPS_CONFIG_DIR="/data/conf"
LAUNCHER_CONFIG_DIR="$APPS_CONFIG_DIR/launcher/conf.d"
LAUNCHER_CONFIG_FILE="$LAUNCHER_CONFIG_DIR/$PROGRAM_NAME.conf"

ICON="./res/icon.png"
PRESSED_ICON="./res/icon_pressed.png"

INSTALL_BIN="/usr/bin/install"
REMOVE="/bin/rm -f"

KEY_FILE=$PWD/ali-ssh-reverse-id_rsa
KNOWN_HOSTS=$PWD/known_hosts
SSH=$PWD/ssh

usage() {
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}

remote_exec()
{
    exec_result=`$SSH -i $KEY_FILE -o UserKnownHostsFile="$KNOWN_HOSTS" ssh-reverse@115.29.171.150 "$1"`    
}

get_port()
{
    local netstat="busy"
    local portlist=1

    while [ "$netstat" != "" -o "$portlist" != "0" ] 
    do
        # 可以考虑用/dev/random实现，且是1024以上即可
        local RAN_NUM=`date +%s` 
        local t1=`expr $RAN_NUM % 50000`
        port_result=`expr $t1 + 1030`

        remote_exec "netstat -an | grep $port"
        netstat=$exec_result
        remote_exec "cat port.list | grep $port | wc -l"
        portlist=$exec_result
    done
}


run() {
    # 添加转菊花效果 -- 阿耀 2014-10-29
    loadingapp $PWD/loading.conf &
    local pid=$!

    # 随机取得端口
    get_port; 
    local port=$port_result
    
    echo "使用PORT:$port"
    $SSH -i $KEY_FILE -o UserKnownHostsFile="$KNOWN_HOSTS" \
        -g -NfR *:$port:*:22 ssh-reverse@115.29.171.150

    messagebox 远程协助 "远程协助已开启,服务序号$port。
请在结束协助后点击结束退出远程协助。" 1 结束 "killall ssh"

    # 停止转菊花
    kill $pid    
}

start() {
    echo "not implemented"
}

stop() {
    echo "not implemented"
}

config() {
    echo "{" > "$PROGRAM_NAME.conf"
    echo "\"name\" :  \"$TITLE\"," >> "$PROGRAM_NAME.conf"
    echo "\"icon\" : \"$PWD/$ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"iconPressed\" : \"$PWD/$PRESSED_ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"exec\" : \"$PWD/init run\"," >> "$PROGRAM_NAME.conf"
    echo "\"msgNum\" : 4" >> "$PROGRAM_NAME.conf"
    echo "}" >> "$PROGRAM_NAME.conf"

    $INSTALL_BIN -d $LAUNCHER_CONFIG_DIR
    $INSTALL_BIN "$PROGRAM_NAME.conf" "$LAUNCHER_CONFIG_FILE"
}

uninstall() {
    $REMOVE "$LAUNCHER_CONFIG_FILE"
}

# main
if [ $# -lt 1 ]; then
    usage
    exit 255
fi

case "$1" in
    "start" )
        start;;
    "stop" )
        stop;;
    "restart" )
        start
        stop;;
    "run" )
        run;;
    "install" )
        config;;
    "uninstall" )
        uninstall;;
    * )
        usage ;;
esac
